In [2]:
import numpy as np
from numpy import linalg as LA

def gauss_seidel(A,b,nmax,tol):
    L = np.tril(A)
    U = A-L
    n = len(b)
    x=np.zeros(n)
    k = 0
    error = 10
    
    while (k < nmax and tol < error):
        xnew = np.dot(LA.inv(L),b-np.dot(U,x))
        error = LA.norm(xnew-x)
        print( "-----------------")
        print("Solucion x para la iteracion k = %2d con error = %5.4f"%(k,error))
        print(xnew)
        x=xnew
        k += 1
    if k==nmax:
        print("maximo numero de iteraciones fue alcanzado. ")
        print("probablemente no hay convergencia")
        

In [ ]:
A = np.array([[5.,-2.,3.],
             [-3.,8.,1.],
             [-3.,-1.,-6.]])
b = np.array([-1.,4.,0.])

In [4]:
gauss_seidel(A,b,10000,1e-5)

-----------------
Solucion x para la iteracion k =  0 con error = 0.4706
[-0.2         0.425       0.02916667]
-----------------
Solucion x para la iteracion k =  1 con error = 0.1827
[-0.0475      0.47854167 -0.05600694]
-----------------
Solucion x para la iteracion k =  2 con error = 0.0922
[ 0.02502083  0.51638368 -0.09857436]
-----------------
Solucion x para la iteracion k =  3 con error = 0.0514
[ 0.06569809  0.53695858 -0.12234214]
-----------------
Solucion x para la iteracion k =  4 con error = 0.0284
[ 0.08818872  0.54836354 -0.13548828]
-----------------
Solucion x para la iteracion k =  5 con error = 0.0157
[ 0.10063838  0.55467543 -0.1427651 ]
-----------------
Solucion x para la iteracion k =  6 con error = 0.0087
[ 0.10752923  0.5581691  -0.1467928 ]
-----------------
Solucion x para la iteracion k =  7 con error = 0.0048
[ 0.11134332  0.56010284 -0.14902213]
-----------------
Solucion x para la iteracion k =  8 con error = 0.0027
[ 0.11345442  0.56117317 -0.15025607]
-

##  Verificación linalg Alg

In [5]:
from scipy.linalg import solve
print(solve(A,b))

[ 0.11607143  0.5625     -0.15178571]


## Radio Espectral

In [9]:
from numpy.linalg import inv

def radio_espectral(A):
    n = np.size(A,1)
    L = np.tril(A)
    U = A-L
    T = -np.matmul(inv(L),U)
    autovalores=LA.eigvals(T)
    print("T=")
    print(T)
    print ("Autovalores = ",autovalores)
    radio_espectral=max(np.absolute(autovalores))
    print ("radio espectral =", radio_espectral)

In [10]:
radio_espectral(A)

T=
[[-0.          0.4        -0.6       ]
 [-0.          0.15       -0.35      ]
 [-0.         -0.225       0.35833333]]
Autovalores =  [-0.         -0.04516708  0.55350042]
radio espectral = 0.5535004175943635


## implementacion escalar

In [12]:
def gauss_seidel_es(A,b,nmax,tol):
    n = len(b)
    x = np.zeros(n)
    xnew = np.zeros(n)
    
    k=0
    error = 10
    
    while(k< nmax and tol < error):
        for i in range(n):
            S=0
            xnew[i]=x[i]
            for j in range(n):
                if i != j:
                    S+=A[i][j]*x[j]
            x[i]=(b[i]-S)/A[i][i]
            
        S=0
        for j in range(n):
            S += (xnew[j]-x[j])**2
            
        error=S**(0.5)
        print ("---------")
        print("Solucion x para la iteracion k = %2d con error = %5.4f"%(k,error))
        print(xnew)
        k+=1

In [13]:
gauss_seidel_es(A,b,100,1e-3)

---------
Solucion x para la iteracion k =  0 con error = 0.4706
[0. 0. 0.]
---------
Solucion x para la iteracion k =  1 con error = 0.1827
[-0.2         0.425       0.02916667]
---------
Solucion x para la iteracion k =  2 con error = 0.0922
[-0.0475      0.47854167 -0.05600694]
---------
Solucion x para la iteracion k =  3 con error = 0.0514
[ 0.02502083  0.51638368 -0.09857436]
---------
Solucion x para la iteracion k =  4 con error = 0.0284
[ 0.06569809  0.53695858 -0.12234214]
---------
Solucion x para la iteracion k =  5 con error = 0.0157
[ 0.08818872  0.54836354 -0.13548828]
---------
Solucion x para la iteracion k =  6 con error = 0.0087
[ 0.10063838  0.55467543 -0.1427651 ]
---------
Solucion x para la iteracion k =  7 con error = 0.0048
[ 0.10752923  0.5581691  -0.1467928 ]
---------
Solucion x para la iteracion k =  8 con error = 0.0027
[ 0.11134332  0.56010284 -0.14902213]
---------
Solucion x para la iteracion k =  9 con error = 0.0015
[ 0.11345442  0.56117317 -0.1502560

## Ejercicio de no convergencia

In [31]:
A = np.array([[1.,3.],[3.,1.]])
b= np.array([-1.,4.])
gauss_seidel_es(A,b,100,1e-5)


---------
Solucion x para la iteracion k =  0 con error = 7.0711
[0. 0.]
---------
Solucion x para la iteracion k =  1 con error = 66.4078
[-1.  7.]
---------
Solucion x para la iteracion k =  2 con error = 597.6705
[-22.  70.]
---------
Solucion x para la iteracion k =  3 con error = 5379.0343
[-211.  637.]
---------
Solucion x para la iteracion k =  4 con error = 48411.3087
[-1912.  5740.]
---------
Solucion x para la iteracion k =  5 con error = 435701.7783
[-17221.  51667.]
---------
Solucion x para la iteracion k =  6 con error = 3921316.0047
[-155002.  465010.]
---------
Solucion x para la iteracion k =  7 con error = 35291844.0419
[-1395031.  4185097.]
---------
Solucion x para la iteracion k =  8 con error = 317626596.3775
[-12555292.  37665880.]
---------
Solucion x para la iteracion k =  9 con error = 2858639367.3978
[-1.12997641e+08  3.38992927e+08]
---------
Solucion x para la iteracion k = 10 con error = 25727754306.5804
[-1.01697878e+09  3.05093635e+09]
---------
Solucion