# Algoritmo para resolver el sistema $Ax = b$ por el método de iteraciones de jacobi

In [1]:
import numpy as np
from numpy import linalg as LA

In [3]:
def Jacobi(A,b,nmax,tol):
    n = len(b)
    D=np.diag(A)
    LU = A-np.diag(D)
    x = np.zeros(n)
    k = 0
    error = 10
    while(k<nmax and tol < error):
        
        xnew = (b-np.dot(LU,x))/D
        error = LA.norm(xnew-x)
        print ("---------")
        print("Solucion x para la iteracion k = %2d con error = %5.4f"%(k,error))
        print(xnew)
        x = xnew
        k+=1
        
    if k==nmax:
        print("maximo numero de iteraciones fue alcanzado. ")
        print("probablemente no hay convergencia")

In [4]:
A = np.array([[5.,-2.,3.],[-3.,8.,1.],[-3.,-1.,-6.]])
b = np.array([-1.,4.,0.])

In [6]:
nmax = 100
tol = 0.001
Jacobi(A,b,nmax,tol)

---------
Solucion x para la iteracion k =  0 con error = 0.5385
[-0.2  0.5 -0. ]
---------
Solucion x para la iteracion k =  1 con error = 0.2142
[0.         0.425      0.01666667]
---------
Solucion x para la iteracion k =  2 con error = 0.1207
[-0.04        0.49791667 -0.07083333]
---------
Solucion x para la iteracion k =  3 con error = 0.0821
[ 0.04166667  0.49385417 -0.06298611]
---------
Solucion x para la iteracion k =  4 con error = 0.0503
[ 0.03533333  0.52349826 -0.10314236]
---------
Solucion x para la iteracion k =  5 con error = 0.0361
[ 0.07128472  0.5261428  -0.10491638]
---------
Solucion x para la iteracion k =  6 con error = 0.0231
[ 0.07340694  0.53984632 -0.12333283]
---------
Solucion x para la iteracion k =  7 con error = 0.0171
[ 0.08993822  0.54294421 -0.12667786]
---------
Solucion x para la iteracion k =  8 con error = 0.0115
[ 0.0931844   0.54956157 -0.13545981]
---------
Solucion x para la iteracion k =  9 con error = 0.0087
[ 0.10110051  0.55187663 -0.1381

## Verificacion

In [ ]:
from scipy.linalg import solve
print(solve(A,b))

## implementacion escalar

In [8]:

import numpy as np
def Jacobi2(A,b,nmax,tol):
    n = len(b)
    x=np.zeros(n)
    xnew=np.zeros(n)
    error = 10
    
    for k in range(nmax):
        for i in range(n):
            xnew[i]=0
            for j in range(n):
                if i != j:
                    xnew[i] += A[i][j]*x[j]
            xnew[i]=(b[i]-xnew[i])/A[i][i]
        S = 0
        for j in range(n):
            S+=(xnew[j]-x[j])**2
        error=S**(0.5)
        print ("---------")
        print("Solucion x para la iteracion k = %2d con error = %5.4f"%(k,error))
        print(xnew)
        
        if error<tol:
            break
        for i in range(n):
            x[i]=xnew[i]

In [9]:
nmax = 100
tol = 0.001
Jacobi(A,b,nmax,tol)

---------
Solucion x para la iteracion k =  0 con error = 0.5385
[-0.2  0.5 -0. ]
---------
Solucion x para la iteracion k =  1 con error = 0.2142
[0.         0.425      0.01666667]
---------
Solucion x para la iteracion k =  2 con error = 0.1207
[-0.04        0.49791667 -0.07083333]
---------
Solucion x para la iteracion k =  3 con error = 0.0821
[ 0.04166667  0.49385417 -0.06298611]
---------
Solucion x para la iteracion k =  4 con error = 0.0503
[ 0.03533333  0.52349826 -0.10314236]
---------
Solucion x para la iteracion k =  5 con error = 0.0361
[ 0.07128472  0.5261428  -0.10491638]
---------
Solucion x para la iteracion k =  6 con error = 0.0231
[ 0.07340694  0.53984632 -0.12333283]
---------
Solucion x para la iteracion k =  7 con error = 0.0171
[ 0.08993822  0.54294421 -0.12667786]
---------
Solucion x para la iteracion k =  8 con error = 0.0115
[ 0.0931844   0.54956157 -0.13545981]
---------
Solucion x para la iteracion k =  9 con error = 0.0087
[ 0.10110051  0.55187663 -0.1381

## Radio espectral

In [16]:
from numpy.linalg import inv

def radio_espectral(A):
    n = np.size(A,1)
    D= np.diag(A)
    LU = A-np.diag(D)
    T = -np.matmul(inv(np.diag(D)),LU)
    autovalores=LA.eigvals(T)
    print("T=")
    print(T)
    print ("Autovalores = ",autovalores)
    radio_espectral=max(np.absolute(autovalores))
    print ("radio espectral =", radio_espectral)

In [17]:
radio_espectral(A)

T=
[[-0.          0.4        -0.6       ]
 [ 0.375      -0.         -0.125     ]
 [-0.5        -0.16666667 -0.        ]]
Autovalores =  [ 0.74481338 -0.60644324 -0.13837014]
radio espectral = 0.7448133799005094
